### ISSUE TITLE
Add Console command

### ISSUE THREAD

**Issue by Costya-Y** [QualiSystems/OpenStack-Cloud-Provider-Shell-2G#2]
In case we deploy vnf without any configuration, we will need to have a possibility to access it over the serial console

**Comment by Costya-Y** [comment]
Console:
Parameters:
    Console Type:
        Instance Console
        Serial Console
        Serial Websocket Console
        
    Return link or ip:port

**Comment by saklar13** [comment]
implemented in [v1.0.0](https://github.com/QualiSystems/OpenStack-Cloud-Provider-Shell-2G/releases/tag/1.0.0)
